Repository Trip-Transfer-Trade/frontend, pull requests merged in 2025-03, with the labels that each got.

#75 [feat/#74-get-history] 입출금 내역 조회 페이지
  src/apis/exchanges.js
  src/pages/UserPage/HistoryItem.jsx
  src/pages/UserPage/HistoryPage.jsx
  src/routers/UserRouter.jsx
Labels: enhancement

#77 [feat/#76-connect-transaction] 송금하기 api 연결
  src/apis/exchanges.js
  src/pages/LoginPage/LoginPage.jsx
  src/pages/UserPage/TransferConfirmPage.jsx
  src/pages/UserPage/TransferRecipientPage.jsx
Labels: enhancement

#79 hotfix : modify apiClient route
  src/redux/signupSlice.js
Labels: bug

#80 Feat/#78 main page
  public/assets/images/main/Dart.svg
  public/assets/images/main/accountComplete.svg
  public/assets/images/main/loginBefore.svg
  public/assets/images/main/tripGoal.svg
  src/apis/accounts.js
  src/apis/exchanges.js
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MainPage/AccountComplete.jsx
  src/pages/MainPage/AccountComplete.module.css
  src/pages/MainPage/CreateAccount.jsx
  src/pages/MainPage/CreateAccount.module.css
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.module.css
  src/redux/signupSlice.js
  src/routers/MainRouter.jsx
Labels: enhancement

#81 Feat : alert after transaction(#76)
  src/pages/UserPage/TransferConfirmPage.jsx
Labels: enhancement

#85 Feat/#84 login status
  src/ context/AuthProvider.jsx
  src/App.jsx
  src/apis/accounts.js
  src/layout/Footer.jsx
  src/pages/MainPage/MainPage.module.css
  src/pages/MyTripPage/TripMainPage.jsx
  src/pages/UserPage/UserPage.jsx
Labels: enhancement

#89 [Feat/#87 connect sms] 전화번호 인증 api 연결
  src/apis/users.js
  src/context/AuthProvider.jsx
  src/pages/SignUpPage/SignupFlow.jsx
Labels: enhancement

#93 Feat/#92 mypage
  src/apis/users.js
  src/pages/MyTripPage/TripCard.jsx
  src/pages/UserPage/ProfilePage.jsx
  src/pages/UserPage/UserPage.jsx
  src/routers/UserRouter.jsx
Labels: enhancement

#94 [Feat/#74 connect balance] 입출금 내역 - 전체 계좌/잔액 조회 연결
  src/components/UserComponent/AccountItem.jsx
  src/components/UserComponent/HistoryItem.jsx
  src/pages/UserPage/HistoryPage.jsx
  src/pages/UserPage/MyAccountPage.jsx
  src/routers/UserRouter.jsx
Labels: enhancement

#121 [Feat/#120 connect goal exchange]
  src/apis/exchanges.js
  src/apis/trips.js
  src/components/ExchangeComponent/ExchangCompleteResultCard.jsx
  src/pages/ExchangePage/ExchangeCompletePage.jsx
  src/pages/ExchangePage/ExchangeMethodPage.jsx
  src/pages/MyTripPage/TripGoal/FailedPage.jsx
  src/pages/MyTripPage/TripGoal/SuccessPage.jsx
Labels: enhancement

#124 Feat/#63 tripgoal page
  src/components/ModalCenter.jsx
  src/components/portfolio/AssetList.jsx
  src/pages/MyTripPage/AccountCard.jsx
  src/pages/MyTripPage/EnterAmountPage.jsx
  src/pages/MyTripPage/TransferPage.jsx
  src/pages/MyTripPage/TripCard.jsx
  src/pages/MyTripPage/TripList.jsx
  src/pages/MyTripPage/TripMainPage.jsx
  src/pages/PortfolioPage/GoalProgressPage.jsx
  src/pages/PortfolioPage/PortfolioAccount.jsx
  src/pages/PortfolioPage/PortfolioChart.jsx
  src/pages/PortfolioPage/PortfolioHeader.jsx
  src/pages/PortfolioPage/PortfolioPage.jsx
  src/pages/PortfolioPage/test.jsx
  src/redux/accountSlice.js
  src/redux/assetsSlice.js
  src/redux/nomalAccountSlice.js
  src/redux/store.js
  src/redux/tripSlice.js
Labels: enhancement

#125 Fix : modify signup flow with phone verify api(#87)
  src/pages/SignUpPage/SignupFlow.jsx
Labels: bug, enhancement

#139 [feat : save fcm token(#9)] fcm 토큰 저장
  src/apis/users.js
  src/firebase.js
Labels: enhancement

#145 [Fix : add currency] currency code 추가
  src/components/ExchangeComponent/ExchangeCardSlider.jsx
  src/pages/ExchangePage/ExchangeCompletePage.jsx
Labels: enhancement

#149 [Feat/#148 ranking] 전체 랭킹 / 유사 목표 랭킹 api 연결 및 페이지 구현
  src/apis/exchanges.js
  src/pages/MainPage/TopPortfolio.jsx
  src/pages/PortfolioPage/RankingPage.jsx
Labels: enhancement

#156 [feat : notification click event] 알림 종류 별 경로 처리
  public/firebase-messaging-sw.js
Labels: enhancement

#165 [Fix/#148 trip rank] 목표 랭킹 없을 시 전체 랭킹 렌더링
  src/pages/ExchangePage/GoalTabContent.jsx
  src/pages/MainPage/TopPortfolio.jsx
  src/pages/PortfolioPage/RankingPage.jsx
Labels: enhancement

#170 [Fix/#78-init-amount] 일반 계좌 생성 시 초기 잔액 설정
  src/apis/exchanges.js
  src/pages/MainPage/CreateAccount.jsx
Labels: enhancement

#177 [Feat/#155 connect alarm] 알림 api 연결
  src/apis/alarms.js
  src/components/UserComponent/NotificationItem.jsx
  src/pages/UserPage/AlarmHistoryPage.jsx
Labels: enhancement

#186 [fix/#185-exchange-except] exchange currency case 별 로직 처리
  src/components/ExchangeComponent/ExchangeCardSlider.jsx
Labels: bug, enhancement

#187 [Fix/#161-connect-data] 목표 도달/실패 연결 & 일괄 매도로 연결
  src/pages/MyTripPage/TripGoal/FailedPage.jsx
  src/pages/MyTripPage/TripGoal/SuccessPage.jsx
Labels: bug

#188 [Fix/#14 modify design] 서비스 안내 페이지 디자인 수정 & 폰트 수정
  src/pages/ExchangePage/ExchangeMethodPage.jsx
  src/pages/MyTripPage/SuccessPage.jsx
  src/pages/MyTripPage/TripGoal/FailedPage.jsx
  src/pages/MyTripPage/TripGoal/InfoPage.jsx
  src/pages/MyTripPage/TripGoal/SuccessPage.jsx
Labels: bug, enhancement

#189 [fix/#148-design] 랭킹 수정
  src/pages/MainPage/TopPortfolio.jsx
  src/pages/PortfolioPage/RankingPage.jsx
  src/pages/PortfolioPage/SuggestPortfolioPage.jsx
  src/routers/TripRouter.jsx
Labels: bug, enhancement

#198 [Fix/#137 goal sell] 일괄 매도 결과 페이지 api 연결
  src/apis/exchanges.js
  src/pages/PortfolioPage/GoalSellSuccessPage.jsx
Labels: enhancement

#201 feat: get flag(#137)
  src/components/ExchangeComponent/ExchangCompleteResultCard.jsx
  src/pages/ExchangePage/ExchangeCompletePage.jsx
Labels: enhancement

#213 Feat/#212 connect transfer
  src/apis/users.js
  src/components/UserComponent/AccountItem.jsx
  src/pages/MainPage/TopPortfolio.jsx
  src/pages/PortfolioPage/RankingPage.jsx
  src/pages/UserPage/MyAccountPage.jsx
  src/pages/UserPage/TransferAmountPage.jsx
  src/pages/UserPage/TransferConfirmPage.jsx
  src/pages/UserPage/TransferRecipientPage.jsx
Labels: bug, enhancement
